### ISSUE TITLE
Generate diagram without need for graphviz

### ISSUE THREAD

**Issue by ChMThiel** [jboz/living-documentation#64]
Hello,
Great tool you created here! But since a few years plantUml supports diagram-generation without the need of a installed graphWiz (see https://docs-as-co.de/news/plantuml-without-graphviz/ for example). This is a nice feature, especially for use on ci/cd buildmachines. 

It would be great, if you were able to support this feature. And this is really easy to accomplish:
Just append after the '@startuml'-tag in the puml-String an new line with '!pragma graphviz_dot jdot'.

Thanks for your help!

**Comment by jboz** [comment]
Nice idea, thanks.
Is it working with header option ?
`<diagramHeader>${project.basedir}/src/main/livingdoc/diagram.header</diagramHeader>`

**Comment by ChMThiel** [comment]
Hello,

using the diagramHeader-Parameter did the job. This works for me.

Thank you!

best regards

Christianb


Am Fr., 11. Sept. 2020 um 12:14 Uhr schrieb jboz <notifications@github.com>:

**Comment by jboz** [comment]
I integrated smetana image processor as the default behavior. Thanks for your contribution 😊
